### PR TITLE
Remove asdl

### PR DESCRIPTION
**Pull request by konstin**
This removes the ASDL code generation in favor of handwriting the AST. 

The motivations for moving away from the ASDL are:

* CPython compatibility is no longer a goal
* The ASDL grammar isn't as expressive as we would like
* The codegen scripts have a high complexity which makes extensions time consuming
* We don't make heavy use of code generation (compared to e.g. RustPython that generates Pyo3 bindings, a fold implementation etc). 

We may want to revisit a grammar based code generation in the future, e.g. by using [ungrammar](https://github.com/rust-analyzer/ungrammar)

### CODE REVIEW

**Comment by konstin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #20** <a href="https://app.graphite.dev/github/pr/astral-sh/RustPython-Parser/20" target="_blank">Graphite</a> 
    * **PR #21** <a href="https://app.graphite.dev/github/pr/astral-sh/RustPython-Parser/21" target="_blank">Graphite</a>  👈
      * **PR #22** <a href="https://app.graphite.dev/github/pr/astral-sh/RustPython-Parser/22" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/RustPython-Parser/21?utm_source=stack-comment).

**Review by MichaReiser — APPROVED** [review]
LGTM. Please extend the PR summary with why using the ASDL was more trouble for us than it is worth (CPython AST compatibility is a non-goal, limited grammar, complicated code gen scripts, ..).

**Comment by davidszotten** [comment]
👋 what's the plan for integrating this into ruff? i'm trying to add an unrelated commit to this repo but this commit fails the ruff test suite when i bring it in there 

```diff
         "RUF012",
         "RUF013",
<        "RUF014",
         "RUF015",
         "RUF016",

[...]
failures:
    generate_json_schema::tests::test_generate_json_schema
```

**Comment by konstin** [comment]
@davidszotten it's not related to this PR, the problem is https://github.com/astral-sh/ruff/pull/5832. `--all-features` should hopefully do as a workaround in the meantime

**Pull request merged**
