### PR TITLE
Avoid lexing magic command when not an identifier

### PR DESCRIPTION
**Pull request by dhruvmanila**
Avoid lexing magic command when the prefix is not followed by a valid identifier start character. This is considered as an error by the original implementation:

```python
t.transform_cell("% foo")
# "get_ipython().run_line_magic('', 'foo')\n"

# % foo
# UsageError: Line magic function `%` not found.
```

A few things to note:
* For `var = % foo`, a parse error will be raised while for `var = ! foo` a lex error will be raised because there's no `!` token, it's only valid in `!=` context
* For `?` prefix (`? foo`), a lex error will be raised while for other prefix a parse error will be raised because there's no `?` token

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Current dependencies on/for this PR:
* main
  * **PR #30** <a href="https://app.graphite.dev/github/pr/astral-sh/RustPython-Parser/30" target="_blank">Graphite</a> 
    * **PR #39** <a href="https://app.graphite.dev/github/pr/astral-sh/RustPython-Parser/39" target="_blank">Graphite</a>  👈
    * **PR #31** <a href="https://app.graphite.dev/github/pr/astral-sh/RustPython-Parser/31" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/RustPython-Parser/39?utm_source=stack-comment).

**Comment by dhruvmanila** [comment]
Right, if we don't allow this (current PR), then we can't allow an empty command either:
```python
%
!
```

Earlier, we were lexing it with an empty string.

I'm kinda leaning towards allowing this while lexing as it's not a parse error from IPython but a usage error which we could highlight and fix using Ruff:

1. `% foo` would be:
	```rust
	MagicCommand {
		value: " foo",
		kind: Magic,
	}
	```
	The linter would check if the command value starts with any whitespace and throw a violation. The fix would be to remove them.

2. `%` would be:
	```rust
	MagicCommand {
		value: "",
		kind: Magic,
	}
	```
	The linter would check if the command value is empty or not. The fix would be remove the statement.

\cc @MichaReiser @konstin

**Comment by konstin** [comment]
can't judge this, i defer to micha

**Comment by MichaReiser** [comment]
> I'm kinda leaning towards allowing this while lexing as it's not a parse error from IPython but a usage error which we could highlight and fix using Ruff:

Sounds reasonable to me. It also seems a plus to give consistent error messages

**Comment by dhruvmanila** [comment]
> Sounds reasonable to me. It also seems a plus to give consistent error messages

Thanks! Closing this.

**Pull request closed without merging**
